services:
  jupyterhub:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000" # JupyterHub default port
      - "5000:5000" # Mapping for the Flask Sidecar
    volumes:
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      # - jupyterhub_data:/data
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

  flask-sidecar:
    build:
      context: ./server
      dockerfile: Dockerfile
    network_mode: "service:jupyterlab"
    environment:
      SECRET_KEY: "local-dev-secret"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"