hub:
  extraConfig:
    00-install-native-auth: |
      import subprocess
      import sys
      # This ensures the library is available inside the Hub container
      subprocess.check_call([sys.executable, "-m", "pip", "install", "jupyterhub-nativeauthenticator"])

# Map python config to the Z2JH schema
  config:
    JupyterHub:
      authenticator_class: nativeauthenticator.NativeAuthenticator
    NativeAuthenticator:
      open_signup: true
      import_from_config: true
      enable_signup: true
    Authenticator:
      allowed_users:
        - admin
        - p01
        - p02
      admin_users:
        - admin

# ensure your database persists across pod restarts
  db:
    type: sqlite-pvc
    pvc:
      accessModes:
        - ReadWriteOnce
      storage: 1Gi